### ISSUE TITLE
Translation welcomed.

### ISSUE THREAD

**Issue by luong-komorebi** [LewisVo/Minitask#1]
Currently this app is in English only. Translation to other languages are welcomed.

**Comment by yallrick** [comment]
Here a french translation 👍 

[values.xml.txt](https://github.com/LewisVo/Minitask/files/1246041/values.xml.txt)

**Comment by luong-komorebi** [comment]
@yallrick wow. wow. I am amazed. How did you get here @yallrick. I made this app a while ago and thought no one would be using it since there are many better ones on the store. Your translation just make me speechless and so surprised. Thank you !!!! :love_letter:

**Comment by yallrick** [comment]
You're very welcome ;)

You are the first in tranding developpers, so I took a look at your work. Then I saw your app on Android and I found it very cool so here is my little contribution ! 

Have a nice day ;)

**Comment by luong-komorebi** [comment]
Thank you so much. This is such a great motivation. :smile_cat:
